### ISSUE TITLE
Getting requirements to build wheel did not run successfully

### ISSUE THREAD

**Issue by jqtmviyu** [RanKKI/BangumiBot#25]
使用仓库里的 Dockerfile 构建失败.

同样在 debian12 arm64  中直接使用, pip 安装依赖也有这个问题, 但在ubuntu lts 和 debian11 中却正常安装.

<details>

<summary>log</summary>

```log
25.46   error: subprocess-exited-with-error
25.46
25.46   × Getting requirements to build wheel did not run successfully.
25.46   │ exit code: 1
25.46   ╰─> [48 lines of output]
25.46       running egg_info
25.46       writing lib/PyYAML.egg-info/PKG-INFO
25.46       writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
25.46       writing top-level names to lib/PyYAML.egg-info/top_level.txt
25.46       Traceback (most recent call last):
25.46         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
25.46           main()
25.46         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
25.46           json_out['return_val'] = hook(**hook_input['kwargs'])
25.46         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
25.46           return hook(config_settings)
25.46         File "/tmp/pip-build-env-ex171md5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
25.46           return self._get_build_requires(config_settings, requirements=['wheel'])
25.46         File "/tmp/pip-build-env-ex171md5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
25.46           self.run_setup()
25.46         File "/tmp/pip-build-env-ex171md5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
25.46           exec(code, locals())
25.46         File "<string>", line 288, in <module>
25.46         File "/tmp/pip-build-env-ex171md5/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
25.46           return distutils.core.setup(**attrs)
25.46         File "/tmp/pip-build-env-ex171md5/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
25.46           return run_commands(dist)
25.46         File "/tmp/pip-build-env-ex171md5/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
25.46           dist.run_commands()
25.46         File "/tmp/pip-build-env-ex171md5/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
25.46           self.run_command(cmd)
25.46         File "/tmp/pip-build-env-ex171md5/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
25.46           super().run_command(command)
25.46         File "/tmp/pip-build-env-ex171md5/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
25.46           cmd_obj.run()
25.46         File "/tmp/pip-build-env-ex171md5/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 318, in run
25.46           self.find_sources()
25.46         File "/tmp/pip-build-env-ex171md5/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 326, in find_sources
25.46           mm.run()
25.46         File "/tmp/pip-build-env-ex171md5/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 548, in run
25.46           self.add_defaults()
25.46         File "/tmp/pip-build-env-ex171md5/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 586, in add_defaults
25.46           sdist.add_defaults(self)
25.46         File "/tmp/pip-build-env-ex171md5/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
25.46           super().add_defaults()
25.46         File "/tmp/pip-build-env-ex171md5/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
25.46           self._add_defaults_ext()
25.46         File "/tmp/pip-build-env-ex171md5/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
25.46           self.filelist.extend(build_ext.get_source_files())
25.46         File "<string>", line 204, in get_source_files
25.46         File "/tmp/pip-build-env-ex171md5/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
25.46           raise AttributeError(attr)
25.46       AttributeError: cython_sources
25.46       [end of output]
25.46
25.46   note: This error originates from a subprocess, and is likely not a problem with pip.
25.46 error: subprocess-exited-with-error
25.46
25.46 × Getting requirements to build wheel did not run successfully.
25.46 │ exit code: 1
25.46 ╰─> See above for output.
25.46
25.46 note: This error originates from a subprocess, and is likely not a problem with pip.
25.47
25.47 [notice] A new release of pip is available: 23.0.1 -> 23.3.1
25.47 [notice] To update, run: pip install --upgrade pip
------
Dockerfile:20
--------------------
  18 |         BANGUMI_CACHE_FOLDER=/cache
  19 |
  20 | >>> RUN pip install -r https://raw.githubusercontent.com/RanKKI/Bangumi/main/requirements.txt
  21 |
  22 |     RUN mkdir -p \
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install -r https://raw.githubusercontent.com/RanKKI/Bangumi/main/requirements.txt" did not complete successfully: exit code: 1
```

</details>

**Comment by jqtmviyu** [comment]
### feature request

*  对于mikan, 存在国内url和代理, 会加入自定义 url 功能吗? 

* 还有一个是时间判断, 比如只下载最近三天的, 或者只下载某个时间戳之后的资源. 这样就不会下载一堆自己之前已经下载过的资源.

### bug 

目前似乎遇到一个bug, 我的aria2 是装在路由上的. 硬盘也是挂在路由上的. 硬盘再通过 smb 挂到 局域网服务器再映射进 docker

如果把 重启 redis 和 BangumiBot  , 之前 aria2 的下载信息还在, 就会陷入重复发送下载任务的死循环(也可能是我删了aria2里的下载或删了硬盘里的torrent)

aria2 显示 `downloading same info hash torrent at that moment`, 添加失败

然后 log 开始无限循环 `Failed to add torrent, will retry later` `Added  failed torrents to queue` 

```yml
services:
  bangumi:
    container_name: bangumi
    image: rankki/bangumi@sha256:bf97663e1aef0cfe169421f54cd5aa7e592a964721bea071d1f1f47da12ce1d6
    restart: unless-stopped
    environment:
      - BANGUMI_CHECK_INTERVAL=600
      - BANGUMI_CLIENT_TYPE=aria2
      - BANGUMI_CLIENT_IP=192.168.2.1
      - BANGUMI_CLIENT_PORT=6800
      - BANGUMI_CLIENT_USERNAME=
      - BANGUMI_CLIENT_PASSWORD=
      - BANGUMI_REDIS_HOST=172.17.0.1
      - BANGUMI_REDIS_PORT=6379
      - BANGUMI_REDIS_PASSWORD=
      - BANGUMI_DOWNLOAD_FOLDER=/mnt/h1/aria2
      - BANGUMI_CACHE_FOLDER=/mnt/h1/aria2/cache
      - BANGUMI_MEDIA_FOLDER=/mnt/h1/Bangumi
      - BANGUMI_CONFIG_PATH=/config
      - BANGUMI_SEEDING=0
      - TZ=Asia/Shanghai
      - PUID=0
      - PGID=0
      - UMASK=022
    ports:
      - 8000:8000
    volumes:
      - ./config:/config
      - /mnt/h1:/mnt/h1
      - bangumi:/src/bangumi

volumes:
  bangumi:
```
